name: Update Manifest on Release

on:
  release:
    types: [published]

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      tags: write  # Wichtig für Tag-Update

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release version
        id: release_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          CLEAN_VERSION=${VERSION#v}
          echo "VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
          echo "TAG_NAME=$VERSION" >> $GITHUB_ENV  # Originaler Tag-Name mit 'v'

      - name: Update version in manifest
        run: |
          cd custom_components/octopus_germany
          jq --arg ver "${{ env.VERSION }}" '.version = $ver' manifest.json > temp.json
          mv temp.json manifest.json

      - name: Commit and tag update
        run: |
          # Zur Sicherheit in main wechseln
          git checkout main

          # Nur committen wenn Änderungen vorhanden
          if ! git diff --quiet -- custom_components/octopus_germany/manifest.json; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add custom_components/octopus_germany/manifest.json
            git commit -m "Bump version to ${{ env.VERSION }}"
            
            # Neuen Commit erstellen und pushen
            git push origin main
            
            # Tag auf neuen Commit verschieben
            git tag -f ${{ env.TAG_NAME }}
            git push origin ${{ env.TAG_NAME }} --force
            echo "✅ Version ${{ env.VERSION}} in main UND Release-Tag aktualisiert"
          else
            echo "⚠️ Keine Änderungen in manifest.json"
          fi
