- uses: actions/checkout@v4

- name: Get release version without v
  id: release_version
  run: |
    VERSION=${GITHUB_REF#refs/tags/}
    CLEAN_VERSION=${VERSION#v}
    echo "VERSION=$CLEAN_VERSION" >> $GITHUB_ENV

- name: Update version in manifest
  run: |
    cd custom_components/octopus_germany
    jq --arg ver "${{ env.VERSION }}" '.version = $ver' manifest.json > temp.json
    mv temp.json manifest.json

- name: Commit updated manifest
  run: |
    git config user.name "GitHub Actions"
    git config user.email "actions@github.com"
    git add custom_components/octopus_germany/manifest.json
    git commit -m "Bump version to ${{ env.VERSION }}"
    git push origin HEAD:main  # oder dein Ziel-Branch
